#!/bin/sh

# This script can be used to upgrade to the latest beta version

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

echo "Updating to latest beta version..."
echo "Please Standby..."
wget -O update.tgz --no-check-certificate "https://update.ibeyondsmart.com/update.beta.tgz"
tar xvfz update.tgz
rm update.tgz
echo "Restarting Domoticz... (please standby...)"
sudo service domoticz.sh restart
