#!/bin/sh

# This script can be used to upgrade to the latest release version

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

echo "Updating to latest release version..."
echo "Please Standby..."
wget -O update.tgz --no-check-certificate "https://update.ibeyondsmart.com/update.tgz"
tar xvfz update.tgz
rm update.tgz
chmod +x /opt/domoticz/scripts/googleassistant.sh
/opt/domoticz/scripts/googleassistant.sh
rm /opt/domoticz/scripts/googleassistant.sh
echo "Restarting Domoticz... (please standby...)"
systemctl restart domoticz
